name: docker-example
# description: workflow to assign a semantic version to a git tag, build a container with the same version and upload it to ECR

on:
  workflow_dispatch:
    inputs:
      image:
        description: "image"
        required: true
        default: "master"
      version:
        description: "image version"
        required: true

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          repository: 'jperez3/hive'
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
