name: react-pull-request


on:
  push:
  pull_request:
    # branches: [ main ]
    paths:
    - 'react/tacos/**'

env:
  CI: true

defaults:
  run:
    working-directory: react/tacos

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [ '14', '15' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install Dependencies
      run: yarn install

    - name: Yarn Test
      run: yarn test  
