name: react-release


on:
  release:
    types: [published]

env:
  CI: true

defaults:
  run:
    working-directory: react/tacos

jobs:
  react-release:
    name: react-release
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Install Dependencies
      run: |
      yarn install
      yarn global add surge

    # - name: Update Tacos version
    #   run: sed -i 's/Version:.*/Version v1.1.1/g' src/app.js

    - name: Building Tacos
      run: yarn build

    - name: Linting Tacos
      run: yarn lint

    - name: Testing Tacos
      run: yarn test

    - name: Deploy Tacos to Surge.sh
      run: surge ./build tacos.surge.sh --token ${{secrets.SURGE_TOKEN}}
